user_profile_url: "https://api.github.com/users/{username}"
user_followers_url: "https://api.github.com/users/{username}/followers"
user_gists_url: "https://api.github.com/users/{username}/gists"
user_gist_url: "https://api.github.com/users/{username}/gists/{gist_id}"
user_organization_url: "https://api.github.com/users/{username}/orgs"
user_repos_url: "https://api.github.com/users/{username}/repos"
user_repo_languages_used_url: "https://api.github.com/repos/{username}/{repo_name}/languages"
user_repo_commits_url: "https://api.github.com/repos/{username}/problem-solving/commits"
user_repo_pull_requests_url: "https://api.github.com/repos/{username}/problem-solving/pulls"
